custom:
  - "https://blockstream.info/address/bc1qarlskqtdq4wsdudecktv6g7zqv5jv52at9k5uk"
  - "https://etherscan.io/address/0x03d42691a1f0d9af62899813e1f3937da0f6039b"
  - "https://solscan.io/account/J9jneBCAW8NaoSj5KekxLyxBcYbzNq3F2Wshdar7FHdf"
